/*
 * game_view.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import server.Client;

import model.User;

/**
 *
 * @author  __USER__
 */
public class game_view extends javax.swing.JFrame implements Runnable {

	User u;
	int i;
	Thread myt = new Thread(this);

	/** Creates new form game_view 
	 * @throws ClassNotFoundException 
	 * @throws IOException 
	 * @throws UnknownHostException 
	 * @throws SQLException */
	public game_view(User u, int i) throws UnknownHostException, IOException,
			ClassNotFoundException, SQLException {
		this.u = u;
		this.i = i;
		initComponents();
		this.setLocationRelativeTo(null);
		//指定游戏
		game();
		//按钮下显示
		Store();
		Library();
		Community();
		this.jLabel1.setText(u.getId());
		this.jTextArea1.setEditable(false);
		this.jTextArea2.setEditable(false);
		//轮播图
		imgrote();
		myt.start();
		//侧图
		rightpicture();
		//单个游戏信息
		onegame();
		//个人信息
		person_message();
		//查看评论
		view_commentlist();
		//五星好评
		imgrote1();
		fivestar();
		evaluation();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPanel10 = new javax.swing.JPanel();
		jButton37 = new javax.swing.JButton();
		jButton38 = new javax.swing.JButton();
		jButton39 = new javax.swing.JButton();
		jButton40 = new javax.swing.JButton();
		jButton41 = new javax.swing.JButton();
		jButton42 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jButton6 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jButton8 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel17 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel8 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jPanel2.setBackground(new java.awt.Color(41, 45, 51));

		jPanel3.setBackground(new java.awt.Color(41, 45, 51));

		jButton1.setBackground(new java.awt.Color(41, 45, 51));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 26));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("   \u5546\u5e97  ");
		jButton1.setBorder(null);
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButton1MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jButton1MouseExited(evt);
			}
		});
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(41, 45, 51));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 26));
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("  \u5e93  ");
		jButton2.setBorder(null);
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButton2MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jButton2MouseExited(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(41, 45, 51));
		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 26));
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setText("  \u793e\u533a  ");
		jButton3.setBorder(null);
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButton3MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jButton3MouseExited(evt);
			}
		});

		jLabel1.setBackground(new java.awt.Color(41, 45, 51));
		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("123");

		jLabel4.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel4.setForeground(new java.awt.Color(204, 204, 204));
		jLabel4.setText("\u4f59\u989d\uff1a");

		jLabel5.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel5.setForeground(new java.awt.Color(204, 204, 204));
		jLabel5.setText("jLabel5");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton3)
										.addGap(82, 82, 82)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												117,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel5,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												203, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																35,
																Short.MAX_VALUE)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																35,
																Short.MAX_VALUE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																35,
																Short.MAX_VALUE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));

		jPanel10.setBackground(new java.awt.Color(0, 0, 0));
		jPanel10.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(102, 102, 102)));

		jButton37.setBackground(new java.awt.Color(51, 51, 51));
		jButton37.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton37.setForeground(new java.awt.Color(255, 255, 255));
		jButton37.setText("  \u60a8\u7684\u5546\u5e97 V  ");
		jButton37.setBorder(null);

		jButton38.setBackground(new java.awt.Color(51, 51, 51));
		jButton38.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton38.setForeground(new java.awt.Color(255, 255, 255));
		jButton38.setText("  \u6e38\u620f V  ");
		jButton38.setBorder(null);

		jButton39.setBackground(new java.awt.Color(51, 51, 51));
		jButton39.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton39.setForeground(new java.awt.Color(255, 255, 255));
		jButton39.setText("  \u8f6f\u4ef6 V  ");
		jButton39.setBorder(null);

		jButton40.setBackground(new java.awt.Color(51, 51, 51));
		jButton40.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton40.setForeground(new java.awt.Color(255, 255, 255));
		jButton40.setText("  \u786c\u4ef6 V  ");
		jButton40.setBorder(null);

		jButton41.setBackground(new java.awt.Color(0, 0, 0));
		jButton41.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton41.setForeground(new java.awt.Color(255, 255, 255));
		jButton41.setText("\u89c6\u9891 V ");
		jButton41.setBorder(null);

		jButton42.setBackground(new java.awt.Color(0, 0, 0));
		jButton42.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 22));
		jButton42.setForeground(new java.awt.Color(255, 255, 255));
		jButton42.setText(" \u65b0\u95fb V ");
		jButton42.setBorder(null);

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
				jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout
				.setHorizontalGroup(jPanel10Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel10Layout
										.createSequentialGroup()
										.addComponent(jButton37)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton38)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton39)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton40)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton41)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton42)));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel10Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton37).addComponent(jButton38)
						.addComponent(jButton39).addComponent(jButton40)
						.addComponent(jButton41).addComponent(jButton42)));

		jPanel4.setBackground(new java.awt.Color(41, 45, 51));
		jPanel4.setForeground(new java.awt.Color(204, 204, 204));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Game Name\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("World of Warships");

		jTextArea1.setBackground(new java.awt.Color(41, 45, 51));
		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14));
		jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(4);
		jTextArea1
				.setText("Artifact \u7531\u4f20\u5947\u6e38\u620f\u8bbe\u8ba1\u5e08 Richard Gar\ufb01eld \u548c Valve \u8054\u624b\u5f00\u53d1\uff0c\u65e8\u5728\u4e3a\u96c6\u6362\u5f0f\u5361\u724c\u6e38\u620f\u63d0\u4f9b\u53f2\u4e0a\u6700\u5177\u6df1\u5ea6\u7684\u73a9\u6cd5\u548c\u6700\u9ad8\u4fdd\u771f\u7684\u4f53\u9a8c\u3002");
		jTextArea1.setBorder(null);
		jScrollPane2.setViewportView(jTextArea1);

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u53d1\u884c\u65f6\u95f4\uff1a");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("jLabel7");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u4e0b\u8f7d\u91cf\uff1a");

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("jLabel9");

		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("\u6536\u85cf\u5ea6\uff1a");

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("jLabel11");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("\u53d1\u884c\u5546\uff1a");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel13.setForeground(new java.awt.Color(0, 102, 255));
		jLabel13.setText("jLabel13");

		jButton4.setBackground(new java.awt.Color(0, 0, 0));
		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("<");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setBackground(new java.awt.Color(0, 0, 0));
		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton5.setForeground(new java.awt.Color(255, 255, 255));
		jButton5.setText(">");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(0, 0, 0));
		jButton10.setBorder(null);

		jButton12.setBorder(null);

		jLabel18.setFont(new java.awt.Font("宋体", 0, 16));
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("\u4ef7\u683c\uff1a");

		jLabel19.setFont(new java.awt.Font("宋体", 1, 16));
		jLabel19.setForeground(new java.awt.Color(255, 255, 51));
		jLabel19.setText("jLabel19");

		jLabel20.setFont(new java.awt.Font("宋体", 1, 16));
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("\u5143");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																300,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addGroup(
																												jPanel4Layout
																														.createSequentialGroup()
																														.addGap(
																																705,
																																705,
																																705)
																														.addComponent(
																																jButton5))
																										.addComponent(
																												jButton10,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))
																						.addComponent(
																								jButton4))
																		.addGap(
																				34,
																				34,
																				34)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel18)
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addGroup(
																												jPanel4Layout
																														.createSequentialGroup()
																														.addGroup(
																																jPanel4Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(
																																				jLabel6)
																																		.addComponent(
																																				jLabel8))
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addGroup(
																																jPanel4Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				jLabel9)
																																		.addComponent(
																																				jLabel7,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				190,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jLabel11)
																																		.addComponent(
																																				jLabel13,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addGroup(
																																				jPanel4Layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								jLabel19)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addComponent(
																																								jLabel20))))
																										.addGroup(
																												jPanel4Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel12)
																														.addComponent(
																																jLabel10))
																										.addComponent(
																												jButton12,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												404,
																												Short.MAX_VALUE)
																										.addComponent(
																												jScrollPane2)))))
										.addContainerGap(338, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												45,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				186,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel7))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel9))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel11))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								jLabel13)))
														.addComponent(
																jButton10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																419,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton4)
														.addComponent(jButton5)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel18)
																		.addComponent(
																				jLabel19)
																		.addComponent(
																				jLabel20)))
										.addContainerGap(7, Short.MAX_VALUE)));

		jPanel5.setBackground(new java.awt.Color(41, 45, 51));

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel14.setForeground(new java.awt.Color(153, 153, 153));
		jLabel14
				.setText("\u8be5\u4ea7\u54c1\u5728\u60a8\u7684\u63a2\u7d22\u961f\u5217\u4e2d\uff0c\u56e0\u4e3a\u5b83\u6b63\u70ed\u95e8\u3002");

		jButton6.setBackground(new java.awt.Color(41, 69, 89));
		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton6.setForeground(new java.awt.Color(0, 153, 255));
		jButton6.setText("\u6dfb\u52a0\u81f3\u60a8\u7684\u6536\u85cf\u5355");
		jButton6.setBorder(null);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton6ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel5Layout.createSequentialGroup().addGroup(
						jPanel5Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										279,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel14)).addContainerGap(448,
						Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addComponent(jLabel14)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												67,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(25, Short.MAX_VALUE)));

		jPanel6.setBackground(new java.awt.Color(62, 73, 87));

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 26));
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("\u8d2d\u4e70 Artifact");

		jButton8.setBackground(new java.awt.Color(93, 118, 4));
		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton8.setForeground(new java.awt.Color(255, 255, 255));
		jButton8.setText("\u8d2d\u4e70");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton8ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel15,
								javax.swing.GroupLayout.PREFERRED_SIZE, 294,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(443, Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel6Layout.createSequentialGroup().addContainerGap(668,
						Short.MAX_VALUE).addComponent(jButton8)
						.addContainerGap()));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addComponent(
												jLabel15,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton8)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel7.setBackground(new java.awt.Color(41, 45, 51));
		jPanel7.setForeground(new java.awt.Color(51, 51, 51));

		jLabel16.setBackground(new java.awt.Color(255, 255, 255));
		jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel16.setForeground(new java.awt.Color(255, 255, 255));
		jLabel16.setText("\u5173\u4e8e\u8fd9\u6e38\u620f\uff1a");

		jTextArea2.setBackground(new java.awt.Color(41, 45, 51));
		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14));
		jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jTextArea2
				.setText("\u5361\u724c\u6e38\u620f\u65b0\u8d77\u70b9\nArtifact \u4e3a\u4e00\u6b3e\u7531\u4f20\u5947\u6e38\u620f\u8bbe\u8ba1\u5e08 Richard Gar\ufb01eld \u548c Valve \u8054\u624b\u5f00\u53d1\u7684\u6570\u5b57\u5361\u724c\u6e38\u620f\uff0c\u5c06\u6df1\u5ea6\u6218\u7565\u5b89\u6392\u548c\u5bf9\u6297\u6027\u6e38\u620f\u4f53\u9a8c\u4e0e Dota 2 \u7684\u4e30\u5bcc\u6545\u4e8b\u80cc\u666f\u5b8c\u7f8e\u878d\u4e3a\u4e00\u4f53\u3002 \u8fd9\u6b3e\u4e0e\u4f17\u4e0d\u540c\u7684\u96c6\u6362\u5f0f\u5361\u724c\u6e38\u620f\uff0c\u5177\u6709\u4ee4\u4eba\u9707\u64bc\u7684\u89c6\u89c9\u6548\u679c\uff0c\u8ba9\u4eba\u6c89\u6d78\u5176\u4e2d\u3002\n");
		jTextArea2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		jScrollPane3.setViewportView(jTextArea2);

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("\u6d4b\u8bc4\uff1a");

		jTextField1.setBackground(new java.awt.Color(41, 45, 51));
		jTextField1.setForeground(new java.awt.Color(153, 153, 153));
		jTextField1.setText("\u6211\u6765\u8bf4\u4e24\u53e5");
		jTextField1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(255, 255, 255)));

		jButton9.setBackground(new java.awt.Color(0, 102, 153));
		jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton9.setForeground(new java.awt.Color(255, 255, 255));
		jButton9.setText("\u53d1\u9001");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton9ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jTable1.setBackground(new java.awt.Color(102, 102, 102));
		jTable1.setFont(new java.awt.Font("宋体", 0, 18));
		jTable1.setForeground(new java.awt.Color(204, 204, 204));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane4.setViewportView(jTable1);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel16)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				1052,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				30,
																				30,
																				30)
																		.addComponent(
																				jButton9))
														.addComponent(jLabel17)
														.addComponent(
																jScrollPane4)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																1173,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(338, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel16)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel17)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												269,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(10, 10, 10)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton9)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel8.setBackground(new java.awt.Color(41, 45, 51));

		jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21
				.setText("\u5982\u679c\u4f60\u89c9\u5f97\u8fd9\u4e2a\u6e38\u620f\u8fd8\u4e0d\u9519\uff0c\u8bf7\u7ed9\u4e2a\u597d\u8bc4\u5427\uff01");

		jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jLabel22MousePressed(evt);
			}
		});
		jLabel22
				.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
					public void mouseMoved(java.awt.event.MouseEvent evt) {
						try {
							jLabel22MouseMoved(evt);
						} catch (SQLException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						} catch (ClassNotFoundException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
				});

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jLabel22,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel21,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(421, Short.MAX_VALUE)));
		jPanel8Layout
				.setVerticalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addComponent(
												jLabel21,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel22,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												46,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(40, Short.MAX_VALUE)));

		jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("\u5e73\u5747\u7528\u6237\u8bc4\u4ef7\u5ea6\uff1a");

		jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel24.setForeground(new java.awt.Color(0, 102, 204));
		jLabel24.setText("\u5206");

		jLabel25.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48));
		jLabel25.setForeground(new java.awt.Color(255, 255, 0));
		jLabel25.setText("100");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(1220, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGap(299, 299, 299)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel7,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel10,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jPanel6,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel5,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												jPanel2Layout
																														.createSequentialGroup()
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jPanel8,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE))
																										.addGroup(
																												jPanel2Layout
																														.createSequentialGroup()
																														.addGap(
																																106,
																																106,
																																106)
																														.addComponent(
																																jLabel25)
																														.addGap(
																																18,
																																18,
																																18)
																														.addComponent(
																																jLabel24)))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												35,
																												35,
																												35)
																										.addComponent(
																												jLabel23)))))
										.addGap(160, 160, 160)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(108, 108, 108)
										.addComponent(
												jPanel10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												555,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanel8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel23)
																		.addGap(
																				35,
																				35,
																				35)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel25)
																						.addComponent(
																								jLabel24))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(57, Short.MAX_VALUE)));

		jScrollPane1.setViewportView(jPanel2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1912,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 979,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public void evaluation() throws UnknownHostException, IOException,
			ClassNotFoundException {
		Client c = new Client();
		String[][] fivestar = c.view_fivestar(gamename);
		int total = 0;
		int one = 0;
		int two = 0;
		int three = 0;
		int four = 0;
		int five = 0;
		for (int l = 0; l < fivestar.length; l++) {
			if (fivestar[l][2].equals("1")) {
				one++;
			}
			if (fivestar[l][2].equals("2")) {
				two++;
			}
			if (fivestar[l][2].equals("3")) {
				three++;
			}
			if (fivestar[l][2].equals("4")) {
				four++;
			}
			if (fivestar[l][2].equals("5")) {
				five++;
			}
		}
		total = one + two + three + four + five;
		if (total != 0) {
			int ev = (20 * one + 40 * two + 60 * three + 80 * four + 100 * five)
					/ fivestar.length;
			this.jLabel25.setText(String.valueOf(ev));
		}
		if (total == 0) {
			this.jLabel25.setText("100");
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
		new main_view(u).setVisible(true);
	}

	//五星好评
	private void fivestar() throws SQLException, ClassNotFoundException,
			IOException {
		Client c = new Client();
		String[][] fivestar = c.view_fivestar(gamename);
		for (int l = 0; l < fivestar.length; l++) {
			if (fivestar[l][1].equals(u.getUsername())) {
				int n = Integer.parseInt(fivestar[l][2]);
				System.out.println(n);
				this.jLabel22.setIcon(new ImageIcon(img10.get(n - 1)));
			}
		}
	}

	int five = 1;
	int star = 0;

	private void jLabel22MouseMoved(java.awt.event.MouseEvent evt)
			throws SQLException, ClassNotFoundException, IOException {
		// TODO add your handling code here:
		Client c = new Client();
		String[][] fivestar = c.view_fivestar(gamename);
		for (int l = 0; l < fivestar.length; l++) {
			if (fivestar[l][1].equals(u.getUsername())) {
				five = 0;
			}
		}
		if (star == 1) {
			if (five == 1) {
				Client c2 = new Client();
				c2.fivestar(u.getId(), u.getUsername(), String.valueOf(wuxing),
						gamename);
				JOptionPane.showMessageDialog(this, "点评成功！");
			}
		}
	}

	//控制轮播图
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (j == 2) {
			j = 0;
		} else {
			int n = j;
			j = n + 1;
		}
		this.jButton10.setIcon(new ImageIcon(img3.get(j)));
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (j == 0) {
			j = 2;
		} else {
			int n = j;
			j = n - 1;
		}
		this.jButton10.setIcon(new ImageIcon(img3.get(j)));
	}

	//五星好评
	int wuxing = 0;

	private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if (five == 1) {
			int x = evt.getX();
			//System.out.println(x);
			if (x >= 12 && x <= 54) {
				this.jLabel22.setIcon(new ImageIcon(img10.get(0)));
				wuxing = 1;
				star = 1;
			}
			if (x >= 71 && x <= 111) {
				this.jLabel22.setIcon(new ImageIcon(img10.get(1)));
				wuxing = 2;
				star = 1;
			}
			if (x >= 128 && x <= 171) {
				this.jLabel22.setIcon(new ImageIcon(img10.get(2)));
				wuxing = 3;
				star = 1;
			}
			if (x >= 185 && x <= 230) {
				this.jLabel22.setIcon(new ImageIcon(img10.get(3)));
				wuxing = 4;
				star = 1;
			}
			if (x >= 238 && x <= 286) {
				this.jLabel22.setIcon(new ImageIcon(img10.get(4)));
				wuxing = 5;
				star = 1;
			}
		}
		if (five == 0) {
			JOptionPane.showMessageDialog(this, "您已经评价过该游戏了哦！");
		}
	}

	int a;
	ArrayList<Image> img10 = new ArrayList<Image>();

	private void imgrote1() {
		for (int a = 1; a <= 5; a++) {
			Image img22 = new ImageIcon("five_star\\" + a + ".png")
					.getImage().getScaledInstance(this.jLabel22.getWidth(),
							this.jLabel22.getHeight(), Image.SCALE_SMOOTH);
			img10.add(img22);
		}
		this.jLabel22.setIcon(new ImageIcon(img10.get(0)));
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException, SQLException {
		// TODO add your handling code here:
		int pd2 = 1;
		Client c1 = new Client();
		Object[][] persongame = (Object[][]) c1.persongame(u.getId());
		for (int z = 0; z < persongame.length; z++) {
			if (persongame[z][2].equals(gamename)) {
				pd2 = 0;
			}
		}
		if (pd2 == 1) {
			if (Integer.valueOf(money).intValue() > Integer.valueOf(price)
					.intValue()) {
				String data = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
						.format(new Date());
				Client c = new Client();
				c.buyperson(u.getId(), u.getUsername(), gamename, data);
				//User.buyperson(u.getId(), u.getUsername(), gamename, data);
				int sum = Integer.valueOf(money).intValue()
						- Integer.valueOf(price).intValue();
				String sum1 = String.valueOf(sum);
				Client c5 = new Client();
				c5.buy(u.getId(), sum1);
				//User.buy(u.getId(), sum1);
				Client c3 = new Client();
				String[] mmoney = c3.merchantmoney(merchantname);
				int sum2 = Integer.valueOf(mmoney[4]).intValue()
						+ Integer.valueOf(price).intValue();
				String sum3 = String.valueOf(sum2);
				Client c4 = new Client();
				c4.upmermoney(merchantname, sum3);
				//User.upmerprice(merchantname, sum3);
				Client c8 = new Client();
				String[] gmessage = c8.onegame(gamename);
				int a = Integer.parseInt(gmessage[8]) + 1;
				Client c9 = new Client();
				c9.updownload(gamename, String.valueOf(a));
				JOptionPane.showMessageDialog(this, "购买游戏成功！");
				JOptionPane.showMessageDialog(this, "这是游戏下载地址："+url);
				person_message();
			} else {
				JOptionPane.showMessageDialog(this, "余额不足，请前往个人信息充值处充值！");
			}
		}
		if (pd2 == 0) {
			JOptionPane.showMessageDialog(this, "您已购买过该游戏，无需重复购买！");
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		int pd3 = 1;
		Client c6 = new Client();
		String[][] collection = c6.view_collection(u.getId());
		for (int z = 0; z < collection.length; z++) {
			if (collection[z][2].equals(gamename)) {
				pd3 = 0;
			}
		}
		if (pd3 == 1) {
			Client c7 = new Client();
			c7.collection(u.getId(), u.getUsername(), gamename);
			Client c8 = new Client();
			String[] gmessage = c8.onegame(gamename);
			int a = Integer.parseInt(gmessage[9]) + 1;
			Client c9 = new Client();
			c9.upcollection(gamename, String.valueOf(a));
			JOptionPane.showMessageDialog(this, "收藏成功！");
		}
		if (pd3 == 0) {
			JOptionPane.showMessageDialog(this, "您已收藏过该游戏，无需重新收藏！");
		}
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		Client c1 = new Client();
		if (this.jTextField1.getText() != null) {
			c1.reply(u.getUsername(), this.jTextField1.getText(), gamename);
			view_commentlist();
			JOptionPane.showMessageDialog(this, "评论成功！");
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	String price;
	String merchantname;
	String url;

	//查看游戏
	private void onegame() throws UnknownHostException, IOException,
			ClassNotFoundException {
		Client c = new Client();
		String[] gmessage = c.onegame(gamename);
		this.jLabel3.setText(gmessage[1]);
		this.jTextArea1.setText(gmessage[4]);
		this.jTextArea2.setText(gmessage[4]);
		this.jLabel7.setText(gmessage[6]);
		this.jLabel9.setText(gmessage[8]);
		this.jLabel11.setText(gmessage[9]);
		this.jLabel13.setText(gmessage[7]);
		this.jLabel19.setText(gmessage[2]);
		url = gmessage[3];
		price = gmessage[2];
		merchantname = gmessage[7];
	}

	//查看评论
	private void view_commentlist() throws IOException, ClassNotFoundException {
		Client c1 = new Client();
		Object[][] commentlist = (Object[][]) c1.view_commentlist(gamename);
		String[] tableString = { "id", "评论者", "内容", "对应游戏" };
		if (commentlist != null) {
			this.jTable1.setModel(new DefaultTableModel(commentlist,
					tableString));
			DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
			cr.setHorizontalAlignment(JLabel.CENTER);
			this.jTable1.setDefaultRenderer(Object.class, cr);
		}
	}

	String gamename;

	//指定游戏
	private void game() {
		if (i == 1) {
			gamename = "Artifact";
		}
		if (i == 2) {
			gamename = "War Thunder";
		}
		if (i == 3) {
			gamename = "KILLING FLOOR 2";
		}
	}

	String money;

	private void person_message() throws IOException, ClassNotFoundException {
		Client c = new Client();
		String[] message = c.person_massage(u.getId());
		money = message[5];
		this.jLabel5.setText(money);
	}

	private void jButton3MouseExited(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.Community.setVisible(false);
	}

	private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		Community.show(evt.getComponent(), this.jButton3.getX() - 165, jButton3
				.getY() + 35);
	}

	private void jButton2MouseExited(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.Library.setVisible(false);
	}

	private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		Library.show(evt.getComponent(), this.jButton2.getX() - 105, jButton2
				.getY() + 35);
	}

	private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.Store.setVisible(false);
	}

	private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		Store.show(evt.getComponent(), this.jButton1.getX() + 15, jButton1
				.getY() + 35);
	}

	/**
	 * @param args the command line arguments
	 */

	//商店按钮下显示
	final JPopupMenu Store = new JPopupMenu();

	private void Store() {
		JMenuItem menuItem1 = new JMenuItem("  精选  ");
		JMenuItem menuItem2 = new JMenuItem("  浏览  ");
		JMenuItem menuItem3 = new JMenuItem("  新闻  ");

		Store.add(menuItem1);
		Store.add(menuItem2);
		Store.add(menuItem3);
	}

	//库钮下显示
	final JPopupMenu Library = new JPopupMenu();

	private void Library() {
		JMenuItem menuItem1 = new JMenuItem("  游戏  ");
		JMenuItem menuItem2 = new JMenuItem("  软件  ");
		JMenuItem menuItem3 = new JMenuItem("  下载  ");

		Library.add(menuItem1);
		Library.add(menuItem2);
		Library.add(menuItem3);
	}

	//社区钮下显示
	final JPopupMenu Community = new JPopupMenu();

	private void Community() {
		JMenuItem menuItem1 = new JMenuItem("  讨论  ");
		JMenuItem menuItem2 = new JMenuItem("  市场  ");
		JMenuItem menuItem3 = new JMenuItem("  视频  ");

		Community.add(menuItem1);
		Community.add(menuItem2);
		Community.add(menuItem3);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
			}
		});
	}

	//侧图
	ArrayList<Image> img4 = new ArrayList<Image>();

	private void rightpicture() {
		for (int j = 1; j <= 3; j++) {
			Image img21 = new ImageIcon("image\\主" + j + ".png")
					.getImage().getScaledInstance(this.jButton12.getWidth(),
							this.jButton12.getHeight(), Image.SCALE_SMOOTH);
			img4.add(img21);
		}
		if (i == 1) {
			this.jButton12.setIcon(new ImageIcon(img4.get(0)));
		}
		if (i == 2) {
			this.jButton12.setIcon(new ImageIcon(img4.get(1)));
		}
		if (i == 3) {
			this.jButton12.setIcon(new ImageIcon(img4.get(2)));
		}
	}

	//轮播图
	int j;
	ArrayList<Image> img1 = new ArrayList<Image>();
	ArrayList<Image> img2 = new ArrayList<Image>();
	ArrayList<Image> img3 = new ArrayList<Image>();

	private void imgrote() {
		for (int j = 1; j <= 3; j++) {
			Image img11 = new ImageIcon("images\\a" + j + ".jpg")
					.getImage().getScaledInstance(this.jButton10.getWidth(),
							this.jButton10.getHeight(), Image.SCALE_SMOOTH);
			img1.add(img11);
		}
		for (int j = 1; j <= 4; j++) {
			Image img22 = new ImageIcon("images\\b" + j + ".jpg")
					.getImage().getScaledInstance(this.jButton10.getWidth(),
							this.jButton10.getHeight(), Image.SCALE_SMOOTH);
			img2.add(img22);
		}
		for (int j = 1; j <= 4; j++) {
			Image img33 = new ImageIcon("images\\c" + j + ".jpg")
					.getImage().getScaledInstance(this.jButton10.getWidth(),
							this.jButton10.getHeight(), Image.SCALE_SMOOTH);
			img3.add(img33);
		}
		//this.jButton10.setIcon(new ImageIcon(img1.get(0)));
	}

	public void run() {
		// TODO Auto-generated method stub
		while (true) {
			if (j == 3)
				j = 0;
			if (i == 1) {
				this.jButton10.setIcon(new ImageIcon(img1.get(j)));
			}
			if (i == 2) {
				this.jButton10.setIcon(new ImageIcon(img2.get(j)));
			}
			if (i == 3) {
				this.jButton10.setIcon(new ImageIcon(img3.get(j)));
			}
			//System.out.println(i);

			try {
				Thread.sleep(3000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			j++;
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton38;
	private javax.swing.JButton jButton39;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}