/*
 * main.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class main extends javax.swing.JFrame {

	/** Creates new form main */
	public main() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jButton11 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jPanel9 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jPanel11 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		jButton26 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jPanel12 = new javax.swing.JPanel();
		jButton27 = new javax.swing.JButton();
		jButton28 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jButton29 = new javax.swing.JButton();
		jButton30 = new javax.swing.JButton();
		jButton31 = new javax.swing.JButton();
		jButton32 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jLabel15 = new javax.swing.JLabel();
		jButton33 = new javax.swing.JButton();
		jButton34 = new javax.swing.JButton();
		jButton35 = new javax.swing.JButton();
		jButton36 = new javax.swing.JButton();
		jButton37 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jPanel8 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton22 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jButton7 = new javax.swing.JButton();
		jPanel13 = new javax.swing.JPanel();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel14 = new javax.swing.JPanel();
		jButton38 = new javax.swing.JButton();
		jLabel16 = new javax.swing.JLabel();
		jButton39 = new javax.swing.JButton();
		jButton40 = new javax.swing.JButton();
		jButton41 = new javax.swing.JButton();
		jButton42 = new javax.swing.JButton();
		jButton43 = new javax.swing.JButton();
		jButton44 = new javax.swing.JButton();
		jButton45 = new javax.swing.JButton();
		jButton46 = new javax.swing.JButton();
		jButton47 = new javax.swing.JButton();
		jPanel15 = new javax.swing.JPanel();
		jLabel17 = new javax.swing.JLabel();
		jButton48 = new javax.swing.JButton();
		jButton49 = new javax.swing.JButton();
		jButton50 = new javax.swing.JButton();
		jButton51 = new javax.swing.JButton();
		jButton52 = new javax.swing.JButton();
		jButton53 = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();
		jButton54 = new javax.swing.JButton();
		jButton55 = new javax.swing.JButton();
		jButton56 = new javax.swing.JButton();
		jButton57 = new javax.swing.JButton();
		jButton58 = new javax.swing.JButton();
		jButton59 = new javax.swing.JButton();
		jButton60 = new javax.swing.JButton();
		jLabel19 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(200, 221, 242));

		jPanel2.setBackground(new java.awt.Color(200, 221, 242));

		jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
		jTabbedPane1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		jPanel4.setBackground(new java.awt.Color(26, 72, 99));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("jLabel1");

		jPanel7.setBackground(new java.awt.Color(26, 72, 99));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel3.setForeground(new java.awt.Color(198, 212, 233));
		jLabel3.setText("\u793c\u7269\u5361");

		jButton11.setBackground(new java.awt.Color(26, 72, 99));
		jButton11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jButton11.setForeground(new java.awt.Color(102, 192, 244));
		jButton11.setText("\u73b0\u5df2\u5728F4\u4e0a\u63a8\u51fa");
		jButton11.setBorder(null);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel4.setForeground(new java.awt.Color(198, 212, 233));
		jLabel4.setText("\u63a8\u8350");

		jButton12.setBackground(new java.awt.Color(26, 72, 99));
		jButton12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jButton12.setForeground(new java.awt.Color(102, 192, 244));
		jButton12.setText("\u7531\u597d\u53cb\u63a8\u8350");
		jButton12.setBorder(null);

		jButton13.setBackground(new java.awt.Color(26, 72, 99));
		jButton13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jButton13.setForeground(new java.awt.Color(102, 192, 244));
		jButton13.setText("\u7531\u597d\u53cb\u63a8\u8350");
		jButton13.setBorder(null);

		jButton14.setBackground(new java.awt.Color(26, 72, 99));
		jButton14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jButton14.setForeground(new java.awt.Color(102, 192, 244));
		jButton14.setText("\u7531\u597d\u53cb\u63a8\u8350");
		jButton14.setBorder(null);

		jButton15.setBackground(new java.awt.Color(26, 72, 99));
		jButton15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jButton15.setForeground(new java.awt.Color(102, 192, 244));
		jButton15.setText("\u7531\u597d\u53cb\u63a8\u8350");
		jButton15.setBorder(null);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(jButton11)
														.addComponent(jLabel4)
														.addComponent(jButton12)
														.addComponent(jButton13)
														.addComponent(jButton14)
														.addComponent(jButton15))
										.addContainerGap(121, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton12)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton13)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton14)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton15)
										.addContainerGap(1012, Short.MAX_VALUE)));

		jPanel9.setBackground(new java.awt.Color(24, 34, 39));

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u60a8\u7684\u63a2\u7d22\u961f\u5217");

		jButton20.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\探索.png")); // NOI18N
		jButton20.setBorder(null);

		jButton21.setBackground(new java.awt.Color(24, 34, 39));
		jButton21.setForeground(new java.awt.Color(255, 255, 255));
		jButton21.setText("\u4e86\u89e3\u66f4\u591a");

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addGap(371, 371, 371)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jButton20,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				1137,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel9Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton21)))
										.addContainerGap(2080, Short.MAX_VALUE)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addGap(51, 51, 51)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jButton21))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton20,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												220,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(53, Short.MAX_VALUE)));

		jPanel11.setBackground(new java.awt.Color(27, 40, 56));
		jPanel11.setForeground(new java.awt.Color(255, 255, 255));

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("\u6d4f\u89c8  F4");

		jButton23.setBackground(new java.awt.Color(28, 106, 142));
		jButton23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton23.setForeground(new java.awt.Color(255, 255, 255));
		jButton23.setText("\u65b0\u54c1");

		jButton24.setBackground(new java.awt.Color(28, 106, 142));
		jButton24.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton24.setForeground(new java.awt.Color(255, 255, 255));
		jButton24.setText("\u4f18\u60e0");

		jButton25.setBackground(new java.awt.Color(28, 106, 142));
		jButton25.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton25.setForeground(new java.awt.Color(255, 255, 255));
		jButton25.setText("\u514d\u8d39\u6e38\u620f");

		jButton26.setBackground(new java.awt.Color(28, 106, 142));
		jButton26.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton26.setForeground(new java.awt.Color(255, 255, 255));
		jButton26.setText("\u6309\u7528\u6237\u6807\u7b7e");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u4e3a\u60a8\u5efa\u8bae\u9274\u8d4f\u5bb6");

		jPanel12.setBackground(new java.awt.Color(73, 83, 96));

		jButton27.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\建议头像.png")); // NOI18N

		jButton28.setBackground(new java.awt.Color(150, 181, 6));
		jButton28.setForeground(new java.awt.Color(255, 255, 255));
		jButton28.setText("\u5173\u6ce8");

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9
				.setText("\u5173\u6ce8 \u55f6\u54e9\u55f6\u54e9 - ( \u309c- \u309c)\u3064\u30ed \u4e7e\u676f~\uff0c\u83b7\u5f97\u66f4\u591a\u7c7b\u4f3c\u8bc4\u6d4b\uff01");

		jLabel10.setBackground(new java.awt.Color(198, 122, 223));
		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel10.setForeground(new java.awt.Color(198, 122, 223));
		jLabel10.setText("487,864\n\u540d\u5173\u6ce8\u8005");

		jButton29
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\9c8348a581554f9a86523c8b10f0eec.png")); // NOI18N

		jButton30
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\9c8348a581554f9a86523c8b10f0eec.png")); // NOI18N

		jButton31
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\9c8348a581554f9a86523c8b10f0eec.png")); // NOI18N

		jButton32
				.setIcon(new javax.swing.ImageIcon(
						"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\9c8348a581554f9a86523c8b10f0eec.png")); // NOI18N

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel11.setForeground(new java.awt.Color(51, 102, 255));
		jLabel11.setText("\u63a8\u8350");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel12.setForeground(new java.awt.Color(51, 102, 255));
		jLabel12.setText("\u63a8\u8350");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel13.setForeground(new java.awt.Color(51, 102, 255));
		jLabel13.setText("\u63a8\u8350");

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel14.setForeground(new java.awt.Color(51, 102, 255));
		jLabel14.setText("\u63a8\u8350");

		jTextArea1.setBackground(new java.awt.Color(73, 83, 96));
		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 15));
		jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1
				.setText("\u4e00\u6b3e\u5e73\u53f0\u8df3\u8dc3\u6e38\u620f\uff0c\u50cf\u7d20\u98ce\u683c\u7684\u753b\u9762\u62e5\u6709\u4e0d\u9519\u7684\u7cbe\u7ec6\u5ea6\uff0c\u5728\u8fd9\u6b3e\u6e38\u620f\u4e2d\u6211\u4eec\u53ef\u4ee5\u770b\u5230\u201c\u6d1b\u514b\u4eba\u201d\u201c\u6d1e\u7a9f\u5192\u9669\u201d\u4ee5\u53ca\u201c\u6076\u9b54\u57ce\u201d\u7684\u4e2d\u4f18\u79c0\u5143\u7d20\u7684\u5f71\u5b50\u3002\u89d2\u8272\u7684\u52a8\u4f5c\u7b97\u4e0d\u4e0a\u6781\u4e3a\u6d41\u7a0b\uff0c\u4f46\u662f\u4e5f\u8db3\u591f\u8fde\u8d2f\u3002\u62e5\u6709\u4e0d\u540c\u53d8\u5316\u9636\u6bb5\u4ee5\u53ca\u4e0d\u540c\u653b\u51fb\u5957\u8def\u7684boss\u8bbe\u8ba1\uff0c\u662f\u6e38\u620f\u7684\u4e00\u5927\u4eae\u70b9\uff0c\u589e\u52a0\u4e86\u4e0d\u5c11\u4e50\u8da3\u3002\u5982\u679c\u4f60\u89c9\u5f97\u73b0\u5728\u5176\u4ed6\u6e38\u620f\u603b\u89c9\u5f97\u6b20\u7f3a\u4e00\u4e9b\u6311\u6218\uff0c\u4e0d\u59a8\u8bd5\u4e00\u4e0b\u8fd9\u6b3eplatfoemer\uff0c\u633a\u6709\u6311\u6218\u6027\u7684\u3002");
		jTextArea1.setBorder(null);
		jTextArea1.setDisabledTextColor(new java.awt.Color(73, 83, 96));
		jScrollPane2.setViewportView(jTextArea1);

		jTextArea2.setBackground(new java.awt.Color(73, 83, 96));
		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 15));
		jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jTextArea2
				.setText("\u4e00\u6b3e\u5e73\u53f0\u8df3\u8dc3\u6e38\u620f\uff0c\u50cf\u7d20\u98ce\u683c\u7684\u753b\u9762\u62e5\u6709\u4e0d\u9519\u7684\u7cbe\u7ec6\u5ea6\uff0c\u5728\u8fd9\u6b3e\u6e38\u620f\u4e2d\u6211\u4eec\u53ef\u4ee5\u770b\u5230\u201c\u6d1b\u514b\u4eba\u201d\u201c\u6d1e\u7a9f\u5192\u9669\u201d\u4ee5\u53ca\u201c\u6076\u9b54\u57ce\u201d\u7684\u4e2d\u4f18\u79c0\u5143\u7d20\u7684\u5f71\u5b50\u3002\u89d2\u8272\u7684\u52a8\u4f5c\u7b97\u4e0d\u4e0a\u6781\u4e3a\u6d41\u7a0b\uff0c\u4f46\u662f\u4e5f\u8db3\u591f\u8fde\u8d2f\u3002\u62e5\u6709\u4e0d\u540c\u53d8\u5316\u9636\u6bb5\u4ee5\u53ca\u4e0d\u540c\u653b\u51fb\u5957\u8def\u7684boss\u8bbe\u8ba1\uff0c\u662f\u6e38\u620f\u7684\u4e00\u5927\u4eae\u70b9\uff0c\u589e\u52a0\u4e86\u4e0d\u5c11\u4e50\u8da3\u3002\u5982\u679c\u4f60\u89c9\u5f97\u73b0\u5728\u5176\u4ed6\u6e38\u620f\u603b\u89c9\u5f97\u6b20\u7f3a\u4e00\u4e9b\u6311\u6218\uff0c\u4e0d\u59a8\u8bd5\u4e00\u4e0b\u8fd9\u6b3eplatfoemer\uff0c\u633a\u6709\u6311\u6218\u6027\u7684\u3002");
		jTextArea2.setBorder(null);
		jTextArea2.setDisabledTextColor(new java.awt.Color(73, 83, 96));
		jScrollPane3.setViewportView(jTextArea2);

		jTextArea3.setBackground(new java.awt.Color(73, 83, 96));
		jTextArea3.setColumns(20);
		jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 15));
		jTextArea3.setForeground(new java.awt.Color(204, 204, 204));
		jTextArea3.setLineWrap(true);
		jTextArea3.setRows(5);
		jTextArea3
				.setText("\u4e00\u6b3e\u5e73\u53f0\u8df3\u8dc3\u6e38\u620f\uff0c\u50cf\u7d20\u98ce\u683c\u7684\u753b\u9762\u62e5\u6709\u4e0d\u9519\u7684\u7cbe\u7ec6\u5ea6\uff0c\u5728\u8fd9\u6b3e\u6e38\u620f\u4e2d\u6211\u4eec\u53ef\u4ee5\u770b\u5230\u201c\u6d1b\u514b\u4eba\u201d\u201c\u6d1e\u7a9f\u5192\u9669\u201d\u4ee5\u53ca\u201c\u6076\u9b54\u57ce\u201d\u7684\u4e2d\u4f18\u79c0\u5143\u7d20\u7684\u5f71\u5b50\u3002\u89d2\u8272\u7684\u52a8\u4f5c\u7b97\u4e0d\u4e0a\u6781\u4e3a\u6d41\u7a0b\uff0c\u4f46\u662f\u4e5f\u8db3\u591f\u8fde\u8d2f\u3002\u62e5\u6709\u4e0d\u540c\u53d8\u5316\u9636\u6bb5\u4ee5\u53ca\u4e0d\u540c\u653b\u51fb\u5957\u8def\u7684boss\u8bbe\u8ba1\uff0c\u662f\u6e38\u620f\u7684\u4e00\u5927\u4eae\u70b9\uff0c\u589e\u52a0\u4e86\u4e0d\u5c11\u4e50\u8da3\u3002\u5982\u679c\u4f60\u89c9\u5f97\u73b0\u5728\u5176\u4ed6\u6e38\u620f\u603b\u89c9\u5f97\u6b20\u7f3a\u4e00\u4e9b\u6311\u6218\uff0c\u4e0d\u59a8\u8bd5\u4e00\u4e0b\u8fd9\u6b3eplatfoemer\uff0c\u633a\u6709\u6311\u6218\u6027\u7684\u3002");
		jTextArea3.setBorder(null);
		jTextArea3.setDisabledTextColor(new java.awt.Color(73, 83, 96));
		jScrollPane4.setViewportView(jTextArea3);

		jTextArea4.setBackground(new java.awt.Color(73, 83, 96));
		jTextArea4.setColumns(20);
		jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 15));
		jTextArea4.setForeground(new java.awt.Color(204, 204, 204));
		jTextArea4.setLineWrap(true);
		jTextArea4.setRows(5);
		jTextArea4
				.setText("\u4e00\u6b3e\u5e73\u53f0\u8df3\u8dc3\u6e38\u620f\uff0c\u50cf\u7d20\u98ce\u683c\u7684\u753b\u9762\u62e5\u6709\u4e0d\u9519\u7684\u7cbe\u7ec6\u5ea6\uff0c\u5728\u8fd9\u6b3e\u6e38\u620f\u4e2d\u6211\u4eec\u53ef\u4ee5\u770b\u5230\u201c\u6d1b\u514b\u4eba\u201d\u201c\u6d1e\u7a9f\u5192\u9669\u201d\u4ee5\u53ca\u201c\u6076\u9b54\u57ce\u201d\u7684\u4e2d\u4f18\u79c0\u5143\u7d20\u7684\u5f71\u5b50\u3002\u89d2\u8272\u7684\u52a8\u4f5c\u7b97\u4e0d\u4e0a\u6781\u4e3a\u6d41\u7a0b\uff0c\u4f46\u662f\u4e5f\u8db3\u591f\u8fde\u8d2f\u3002\u62e5\u6709\u4e0d\u540c\u53d8\u5316\u9636\u6bb5\u4ee5\u53ca\u4e0d\u540c\u653b\u51fb\u5957\u8def\u7684boss\u8bbe\u8ba1\uff0c\u662f\u6e38\u620f\u7684\u4e00\u5927\u4eae\u70b9\uff0c\u589e\u52a0\u4e86\u4e0d\u5c11\u4e50\u8da3\u3002\u5982\u679c\u4f60\u89c9\u5f97\u73b0\u5728\u5176\u4ed6\u6e38\u620f\u603b\u89c9\u5f97\u6b20\u7f3a\u4e00\u4e9b\u6311\u6218\uff0c\u4e0d\u59a8\u8bd5\u4e00\u4e0b\u8fd9\u6b3eplatfoemer\uff0c\u633a\u6709\u6311\u6218\u6027\u7684\u3002");
		jTextArea4.setBorder(null);
		jTextArea4.setDisabledTextColor(new java.awt.Color(73, 83, 96));
		jScrollPane5.setViewportView(jTextArea4);

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(
				jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout
				.setHorizontalGroup(jPanel12Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel12Layout
										.createSequentialGroup()
										.addGap(28, 28, 28)
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel12Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton27,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				87,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel9)
																						.addGroup(
																								jPanel12Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton28,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												76,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jLabel10,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												152,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addContainerGap(
																				353,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel12Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton29,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								227,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel11,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								50,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				37,
																				37,
																				37)
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane3)
																						.addComponent(
																								jButton30,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								227,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel12,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								50,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				38,
																				38,
																				38)
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane4)
																						.addComponent(
																								jButton31,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								227,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								50,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				41,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane5)
																						.addComponent(
																								jLabel14,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								50,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton32,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								227,
																								Short.MAX_VALUE))
																		.addGap(
																				55,
																				55,
																				55)))));
		jPanel12Layout
				.setVerticalGroup(jPanel12Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel12Layout
										.createSequentialGroup()
										.addGap(25, 25, 25)
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel12Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel10,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								39,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton28,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)))
														.addComponent(
																jButton27,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																89,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel12Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton32,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				104,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel14))
														.addGroup(
																jPanel12Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				jPanel12Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton29,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								104,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel11))
																		.addGroup(
																				jPanel12Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton30,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								104,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel12))
																		.addGroup(
																				jPanel12Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton31,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								104,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel13))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																323,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																323,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																323,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																323,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(26, 26, 26)));

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("\u70ed\u95e8VR\u6e38\u620f");

		jButton33.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热门1.png")); // NOI18N

		jButton34.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热门2.png")); // NOI18N

		jButton35.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热门3.png")); // NOI18N

		jButton36.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热门4.png")); // NOI18N

		jButton37.setBackground(new java.awt.Color(27, 46, 56));
		jButton37.setForeground(new java.awt.Color(255, 255, 255));
		jButton37.setText("\u6d4f\u89c8\u6240\u6709");

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
				jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout
				.setHorizontalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel11Layout
										.createSequentialGroup()
										.addGap(387, 387, 387)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel11Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton23,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				270,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton24,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				270,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton25,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				270,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton26,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				270,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel12,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel11Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel11Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel15)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton37))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel11Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton33,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								260,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jButton34,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								260,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jButton35,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								260,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jButton36,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								260,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(2537, Short.MAX_VALUE)));
		jPanel11Layout
				.setVerticalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel11Layout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addComponent(jLabel7)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton23,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																62,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton24,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																62,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton25,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																62,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton26,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																62,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(91, 91, 91)
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel12,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												637,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel11Layout
																		.createSequentialGroup()
																		.addGap(
																				57,
																				57,
																				57)
																		.addComponent(
																				jLabel15)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel11Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton37)
																		.addGap(
																				25,
																				25,
																				25)))
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton33,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																154,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton34,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																154,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton35,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																154,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton36,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																154,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(120, Short.MAX_VALUE)));

		jPanel6.setBackground(new java.awt.Color(26, 72, 99));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u7cbe\u9009\u548c\u63a8\u8350");

		jButton8.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\轮播.png")); // NOI18N
		jButton8.setBorder(null);

		jButton9.setBackground(new java.awt.Color(17, 49, 70));
		jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jButton9.setForeground(new java.awt.Color(255, 255, 255));
		jButton9.setText("<");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(17, 49, 70));
		jButton10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jButton10.setForeground(new java.awt.Color(255, 255, 255));
		jButton10.setText(">");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton9)
										.addGap(1, 1, 1)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				1180,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				2,
																				2,
																				2)
																		.addComponent(
																				jButton10)))
										.addContainerGap(111, Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel6Layout
										.createSequentialGroup()
										.addGap(7, 7, 7)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel6Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				483,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addGap(
																				176,
																				176,
																				176)
																		.addComponent(
																				jButton9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				145,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				203,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addGap(
																				172,
																				172,
																				172)
																		.addComponent(
																				jButton10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				152,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				200,
																				Short.MAX_VALUE)))));

		jPanel8.setBackground(new java.awt.Color(26, 72, 99));

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u7279\u522b\u4f18\u60e0");

		jButton16.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\优惠1.png")); // NOI18N
		jButton16.setBorder(null);

		jButton17.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\优惠2.png")); // NOI18N
		jButton17.setBorder(null);

		jButton18.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\优惠3.png")); // NOI18N
		jButton18.setBorder(null);

		jButton19.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\优惠4.png")); // NOI18N
		jButton19.setBorder(null);

		jButton22.setBackground(new java.awt.Color(26, 72, 99));
		jButton22.setForeground(new java.awt.Color(255, 255, 255));
		jButton22.setText("\u6d4f\u89c8\u6240\u6709");

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(70, 70, 70)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																387,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addGap(50, 50, 50)
										.addComponent(
												jButton17,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												383,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(52, 52, 52)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel8Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jButton19,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				380,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton18,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				380,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jButton22))
										.addContainerGap(206, Short.MAX_VALUE)));
		jPanel8Layout
				.setVerticalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																487,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel8Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel8Layout
																						.createSequentialGroup()
																						.addGap(
																								52,
																								52,
																								52)
																						.addComponent(
																								jButton18,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								231,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								25,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton19,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								231,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel8Layout
																						.createSequentialGroup()
																						.addGroup(
																								jPanel8Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel5)
																										.addComponent(
																												jButton22))
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jButton16,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								487,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(115, Short.MAX_VALUE)));

		jPanel5.setBackground(new java.awt.Color(53, 109, 146));
		jPanel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton1.setBackground(new java.awt.Color(53, 109, 146));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("  \u60a8\u7684\u5546\u5e97v  ");
		jButton1.setBorder(null);

		jButton2.setBackground(new java.awt.Color(53, 109, 146));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("    \u6e38\u620fv   ");
		jButton2.setBorder(null);

		jButton3.setBackground(new java.awt.Color(53, 109, 146));
		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setText("    \u8f6f\u4ef6v   ");
		jButton3.setBorder(null);

		jButton4.setBackground(new java.awt.Color(53, 109, 146));
		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("    \u786c\u4ef6v   ");
		jButton4.setBorder(null);

		jButton5.setBackground(new java.awt.Color(53, 109, 146));
		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton5.setForeground(new java.awt.Color(255, 255, 255));
		jButton5.setText("    \u65b0\u95fbv   ");
		jButton5.setBorder(null);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setBackground(new java.awt.Color(53, 109, 146));
		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton6.setForeground(new java.awt.Color(255, 255, 255));
		jButton6.setText("    \u89c6\u9891v   ");
		jButton6.setBorder(null);

		jButton7.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\搜索.png")); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addComponent(jButton1)
										.addGap(1, 1, 1)
										.addComponent(jButton2)
										.addGap(1, 1, 1)
										.addComponent(jButton3)
										.addGap(1, 1, 1)
										.addComponent(jButton4)
										.addGap(1, 1, 1)
										.addComponent(jButton6)
										.addGap(1, 1, 1)
										.addComponent(jButton5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												384, Short.MAX_VALUE)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												235,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(8, 8, 8)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jButton1)
																		.addComponent(
																				jButton2)
																		.addComponent(
																				jButton3)
																		.addComponent(
																				jButton4)
																		.addComponent(
																				jButton6)
																		.addComponent(
																				jButton5)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				28,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel13.setBackground(new java.awt.Color(39, 67, 89));

		jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
		jTabbedPane2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jPanel14.setBackground(new java.awt.Color(39, 67, 89));

		jButton38.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jLabel16.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品4.png")); // NOI18N

		jButton39.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton40.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton41.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton42.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton43.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton44.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton45.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton46.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		jButton47.setIcon(new javax.swing.ImageIcon(
				"D:\\作业2\\Java程序实训\\F_Four\\src\\view\\image\\热品1.png")); // NOI18N

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(
				jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout
				.setHorizontalGroup(jPanel14Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel14Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel14Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel14Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton38,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton39,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton40,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel14Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton42,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton41,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton43,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel14Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton45,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton44,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel14Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton47,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton46,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				773,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel16)
										.addContainerGap()));
		jPanel14Layout
				.setVerticalGroup(jPanel14Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel14Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel14Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jLabel16,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel14Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton38,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton39,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton40,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton41,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton42,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton43,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton44,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton45,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton46,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton47,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				85,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jTabbedPane2.addTab("\u70ed\u54c1\u4e0e\u70ed\u95e8\u5546\u54c1",
				jPanel14);

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel13Layout.createSequentialGroup().addGap(398, 398, 398)
						.addComponent(jTabbedPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1197,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(317, Short.MAX_VALUE)));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel13Layout.createSequentialGroup().addComponent(
						jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
						1001, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(57, Short.MAX_VALUE)));

		jPanel15.setBackground(new java.awt.Color(51, 51, 51));

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("\u4f4e\u4e8e \u00a540 ");

		jButton48.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\低价1.png")); // NOI18N

		jButton49.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\低价1.png")); // NOI18N

		jButton50.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\低价1.png")); // NOI18N

		jButton51.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\低价1.png")); // NOI18N

		jButton52.setBackground(new java.awt.Color(0, 0, 0));
		jButton52.setForeground(new java.awt.Color(255, 255, 255));
		jButton52.setText("\u4f4e\u4e8e \u00a520 ");

		jButton53.setBackground(new java.awt.Color(0, 0, 0));
		jButton53.setForeground(new java.awt.Color(255, 255, 255));
		jButton53.setText("\u4f4e\u4e8e \u00a540 ");
		jButton53.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton53ActionPerformed(evt);
			}
		});

		jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("\u66f4\u65b0\u4e0e\u4f18\u60e0");

		jButton54.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新与优惠1.png")); // NOI18N

		jButton55.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		jButton56.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		jButton57.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		jButton58.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		jButton59.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		jButton60.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\VX50IU9830\\Desktop\\steam\\新建文件夹\\更新.png")); // NOI18N

		javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(
				jPanel15);
		jPanel15.setLayout(jPanel15Layout);
		jPanel15Layout
				.setHorizontalGroup(jPanel15Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel15Layout
										.createSequentialGroup()
										.addGap(404, 404, 404)
										.addGroup(
												jPanel15Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel15Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton54)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel15Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel15Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton55,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton56,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton57,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel15Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton58,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton59,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton60,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												216,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addComponent(jLabel18)
														.addGroup(
																jPanel15Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				jPanel15Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton48,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								283,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								jButton49,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								283,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								jButton50,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								283,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								15,
																								15,
																								15)
																						.addComponent(
																								jButton51,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								283,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel15Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel17)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton53)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jButton52))))
										.addContainerGap(379, Short.MAX_VALUE)));
		jPanel15Layout
				.setVerticalGroup(jPanel15Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel15Layout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addGroup(
												jPanel15Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel15Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel15Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton52)
																						.addComponent(
																								jButton53))
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton51,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				163,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jButton50,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																163,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton49,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																163,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel15Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel17)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				jButton48,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				163,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(70, 70, 70)
										.addComponent(jLabel18)
										.addGap(32, 32, 32)
										.addGroup(
												jPanel15Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton54)
														.addGroup(
																jPanel15Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel15Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton55,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton56,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton57,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				27,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel15Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton58,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton59,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton60,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								255,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(124, Short.MAX_VALUE)));

		jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel19.setForeground(new java.awt.Color(255, 255, 255));
		jLabel19.setText("F4 \u6e38\u620f\u5c0f\u52a9\u624b");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(33, 33, 33)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																251,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(
																				jPanel8,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addGap(
																								63,
																								63,
																								63)
																						.addComponent(
																								jPanel5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jPanel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(2225, 2225, 2225))
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(
												jPanel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(448, Short.MAX_VALUE))
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(
												jPanel13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(2134, Short.MAX_VALUE))
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(
												jPanel15,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
						.addGroup(
								jPanel4Layout.createSequentialGroup().addGap(
										921, 921, 921).addComponent(jLabel19)
										.addContainerGap(2971, Short.MAX_VALUE))
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(
												jPanel11,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout
										.createSequentialGroup()
										.addGap(50, 50, 50)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												158,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel8,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(224, 224, 224)
										.addComponent(
												jPanel13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel15,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(33, 33, 33).addComponent(
												jLabel19).addGap(38, 38, 38)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addComponent(jPanel4,
						javax.swing.GroupLayout.PREFERRED_SIZE, 1959,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addComponent(jPanel4,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("       \u5546\u5e97      ", jPanel3);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addComponent(
						jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						1897, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 5694,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		jScrollPane1.setViewportView(jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1914,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new main().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton27;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton29;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton31;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton33;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton36;
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton38;
	private javax.swing.JButton jButton39;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton40;
	private javax.swing.JButton jButton41;
	private javax.swing.JButton jButton42;
	private javax.swing.JButton jButton43;
	private javax.swing.JButton jButton44;
	private javax.swing.JButton jButton45;
	private javax.swing.JButton jButton46;
	private javax.swing.JButton jButton47;
	private javax.swing.JButton jButton48;
	private javax.swing.JButton jButton49;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton50;
	private javax.swing.JButton jButton51;
	private javax.swing.JButton jButton52;
	private javax.swing.JButton jButton53;
	private javax.swing.JButton jButton54;
	private javax.swing.JButton jButton55;
	private javax.swing.JButton jButton56;
	private javax.swing.JButton jButton57;
	private javax.swing.JButton jButton58;
	private javax.swing.JButton jButton59;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton60;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}