/*
 * management_view.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import model.Management;

import server.Client;

/**
 *
 * @author  __USER__
 */
public class management_view extends javax.swing.JFrame {

	Management m;

	/** Creates new form management_view 
	 * @throws ClassNotFoundException 
	 * @throws IOException */
	public management_view(Management m) throws IOException,
			ClassNotFoundException {
		this.m = m;
		initComponents();
		this.setLocationRelativeTo(null);
		//查看公告
		view_announcement();
		//查看评论
		view_commentlist();
		//查看用户
		view_user();
		//查看商家
		view_merchant();
		//查看游戏
		view_game();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel9 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel10 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jLabel13 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jLabel66 = new javax.swing.JLabel();
		jLabel75 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel76 = new javax.swing.JLabel();
		jButton32 = new javax.swing.JButton();
		jLabel77 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel89 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTable7 = new javax.swing.JTable();
		jLabel90 = new javax.swing.JLabel();
		jLabel91 = new javax.swing.JLabel();
		jLabel92 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jButton36 = new javax.swing.JButton();
		jLabel39 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable5 = new javax.swing.JTable();
		jLabel81 = new javax.swing.JLabel();
		jLabel82 = new javax.swing.JLabel();
		jLabel83 = new javax.swing.JLabel();
		jLabel84 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jButton34 = new javax.swing.JButton();
		jPanel11 = new javax.swing.JPanel();
		jLabel85 = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTable6 = new javax.swing.JTable();
		jLabel86 = new javax.swing.JLabel();
		jLabel87 = new javax.swing.JLabel();
		jLabel88 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jButton35 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(41, 45, 51));

		jLabel1.setBackground(new java.awt.Color(41, 45, 51));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/image/图标.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3
				.setText("\u56e0\u60a8\u7684\u521b\u9020\u800c\u66f4\u52a0\u5b8c\u7f8e");

		jLabel2.setFont(new java.awt.Font("Bauhaus 93", 3, 24));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Because of your creation and more perfect");

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/view/image/建议头像.png"))); // NOI18N

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel5.setForeground(new java.awt.Color(51, 102, 255));
		jLabel5.setText("\u6b22\u8fce\u60a8\uff1a");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6
				.setText("\u611f\u89c9\u4eba\u751f\u8fbe\u5230\u4e86\u5dc5\u5cf0");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel7.setForeground(new java.awt.Color(0, 102, 255));
		jLabel7.setText("\u7ba1\u7406\u8005");

		jTabbedPane1.setBackground(new java.awt.Color(0, 204, 255));
		jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
		jTabbedPane1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));

		jPanel4.setBackground(new java.awt.Color(51, 51, 51));

		jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane1.setViewportView(jTable1);

		jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
		jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

		jPanel9.setBackground(new java.awt.Color(51, 51, 51));

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u6dfb\u52a0\u516c\u544a\u5185\u5bb9\uff1a");

		jButton2.setBackground(new java.awt.Color(102, 102, 102));
		jButton2.setForeground(new java.awt.Color(204, 204, 204));
		jButton2.setText("\u53d1\u5e03\u516c\u544a");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton2ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addGap(45, 45, 45)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel8)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel9Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel9Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								1213,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				62,
																				62,
																				62)))
										.addGap(67, 67, 67)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												132,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												37, Short.MAX_VALUE)
										.addComponent(jButton2).addGap(32, 32,
												32)));

		jTabbedPane2.addTab(" \u6dfb\u52a0\u516c\u544a ", jPanel9);

		jPanel10.setBackground(new java.awt.Color(51, 51, 51));

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel11.setForeground(new java.awt.Color(204, 204, 204));
		jLabel11
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u516c\u544a\u4fe1\u606f\uff0c\u9009\u62e9\u60a8\u8981\u5220\u9664\u7684\u516c\u544a\u7684id\uff0c\u5e76\u586b\u5199\u4e8e\u4e0b\u9762\u4fe1\u606f");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("\u6e29\u99a8\u63d0\u793a\uff1a");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("ID\uff1a");

		jTextField2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton3.setBackground(new java.awt.Color(102, 102, 102));
		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton3.setForeground(new java.awt.Color(204, 204, 204));
		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton3ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
				jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout
				.setHorizontalGroup(jPanel10Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel10Layout
										.createSequentialGroup()
										.addGap(33, 33, 33)
										.addGroup(
												jPanel10Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jSeparator2,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel10Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel12)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel11)))
										.addContainerGap(685, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel10Layout
										.createSequentialGroup()
										.addContainerGap(482, Short.MAX_VALUE)
										.addComponent(jLabel13)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												197,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3).addGap(505,
												505, 505)));
		jPanel10Layout
				.setVerticalGroup(jPanel10Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel10Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel10Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(jLabel11))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(76, 76, 76)
										.addGroup(
												jPanel10Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(108, Short.MAX_VALUE)));

		jTabbedPane2.addTab("  \u5220\u9664\u516c\u544a ", jPanel10);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(81, 81, 81)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jTabbedPane2,
																javax.swing.GroupLayout.Alignment.LEADING,
																0, 0,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																1310,
																Short.MAX_VALUE))
										.addContainerGap(83, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addGap(26, 26, 26)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 315,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								18, 18, 18).addComponent(jTabbedPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 313,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(56, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u516c\u544a\u7ba1\u7406 ", jPanel4);

		jPanel6.setBackground(new java.awt.Color(51, 51, 51));

		jTable3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable3.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable3.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane3.setViewportView(jTable3);

		jLabel66.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel66.setForeground(new java.awt.Color(255, 255, 255));
		jLabel66.setText("\u5220\u9664\u8bc4\u8bba\uff1a");

		jLabel75.setBackground(new java.awt.Color(204, 204, 204));
		jLabel75.setForeground(new java.awt.Color(153, 153, 153));
		jLabel75
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u8bc4\u8bba\u8868\u9009\u62e9\u60a8\u8981\u5220\u9664\u7684\u8bc4\u8bbaid\uff01");

		jTextField4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel76.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel76.setForeground(new java.awt.Color(255, 255, 255));
		jLabel76.setText("ID:");

		jButton32.setBackground(new java.awt.Color(102, 102, 102));
		jButton32.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton32.setForeground(new java.awt.Color(204, 204, 204));
		jButton32.setText("\u5220\u9664");
		jButton32.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton32ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel77.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel77.setForeground(new java.awt.Color(255, 255, 255));
		jLabel77.setText("\u8bc4\u8bba\u4fe1\u606f\uff1a");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(76, 76, 76)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel66)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel75))
														.addComponent(jLabel77)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																1325,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(73, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap(666, Short.MAX_VALUE)
										.addComponent(jLabel76)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton32).addGap(612,
												612, 612)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(45, 45, 45)
										.addComponent(jLabel77)
										.addGap(27, 27, 27)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												260,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(93, 93, 93)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel66)
														.addComponent(jLabel75))
										.addGap(65, 65, 65)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel76)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton32))
										.addContainerGap(141, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u8bc4\u8bba\u7ba1\u7406 ", jPanel6);

		jPanel7.setBackground(new java.awt.Color(51, 51, 51));

		jLabel89.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel89.setForeground(new java.awt.Color(255, 255, 255));
		jLabel89.setText("\u7528\u6237\u4fe1\u606f\uff1a");

		jTable7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable7.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable7.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane7.setViewportView(jTable7);

		jLabel90.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel90.setForeground(new java.awt.Color(255, 255, 255));
		jLabel90.setText("Ban\u7528\u6237\uff1a");

		jLabel91.setForeground(new java.awt.Color(204, 204, 204));
		jLabel91
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u7528\u6237\u4fe1\u606f\u9009\u62e9\u60a8\u8981ban\u7684\u7528\u6237id\u5e76\u586b\u5199ban\u539f\u56e0\uff01");

		jLabel92.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel92.setForeground(new java.awt.Color(255, 255, 255));
		jLabel92.setText("ID\uff1a");

		jTextField8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton36.setBackground(new java.awt.Color(255, 0, 51));
		jButton36.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton36.setForeground(new java.awt.Color(255, 255, 255));
		jButton36.setText("BAN");
		jButton36.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton36ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel39.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel39.setForeground(new java.awt.Color(255, 255, 255));
		jLabel39.setText("\u7406\u7531\uff1a");

		jTextField3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel89)
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel7Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel7Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jScrollPane7,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								1310,
																								Short.MAX_VALUE)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel7Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel39)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												1238,
																												Short.MAX_VALUE))
																						.addComponent(
																								jButton36))
																		.addGap(
																				81,
																				81,
																				81))
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel92)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				101,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel90)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel91)))));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addGap(47, 47, 47)
										.addComponent(jLabel89)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel90)
														.addComponent(jLabel91))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel92)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(21, 21, 21)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				102,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton36))
														.addComponent(jLabel39))
										.addContainerGap(29, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u7528\u6237\u7ba1\u7406 ", jPanel7);

		jPanel8.setBackground(new java.awt.Color(51, 51, 51));

		jTable5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable5.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable5.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane5.setViewportView(jTable5);

		jLabel81.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel81.setForeground(new java.awt.Color(255, 255, 255));
		jLabel81.setText("\u5546\u5bb6\u4fe1\u606f\uff1a");

		jLabel82.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel82.setForeground(new java.awt.Color(255, 255, 255));
		jLabel82.setText("Ban\u5546\u5bb6\uff1a");

		jLabel83.setForeground(new java.awt.Color(204, 204, 204));
		jLabel83
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u5546\u5bb6\u4fe1\u606f\u9009\u62e9\u60a8\u8981ban\u7684\u5546\u5bb6id\uff01");

		jLabel84.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel84.setForeground(new java.awt.Color(255, 255, 255));
		jLabel84.setText("ID\uff1a");

		jTextField6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton34.setBackground(new java.awt.Color(255, 0, 51));
		jButton34.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton34.setForeground(new java.awt.Color(255, 255, 255));
		jButton34.setText("BAN");
		jButton34.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton34ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel8Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel8Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel8Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel82)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel83))
																						.addGroup(
																								jPanel8Layout
																										.createSequentialGroup()
																										.addGap(
																												514,
																												514,
																												514)
																										.addComponent(
																												jLabel84)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												101,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton34)))
																		.addContainerGap())
														.addGroup(
																jPanel8Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel8Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel81)
																						.addContainerGap())
																		.addGroup(
																				jPanel8Layout
																						.createSequentialGroup()
																						.addComponent(
																								jScrollPane5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								1310,
																								Short.MAX_VALUE)
																						.addGap(
																								81,
																								81,
																								81))))));
		jPanel8Layout
				.setVerticalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(47, 47, 47)
										.addComponent(jLabel81)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(67, 67, 67)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel82)
														.addComponent(jLabel83))
										.addGap(78, 78, 78)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel84)
														.addGroup(
																jPanel8Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton34)))
										.addContainerGap(89, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u5546\u5bb6\u7ba1\u7406 ", jPanel8);

		jPanel11.setBackground(new java.awt.Color(51, 51, 51));

		jLabel85.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel85.setForeground(new java.awt.Color(255, 255, 255));
		jLabel85.setText("\u6e38\u620f\u4fe1\u606f\uff1a");

		jTable6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable6.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable6.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane6.setViewportView(jTable6);

		jLabel86.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel86.setForeground(new java.awt.Color(255, 255, 255));
		jLabel86.setText("Ban\u6e38\u620f\uff1a");

		jLabel87.setForeground(new java.awt.Color(204, 204, 204));
		jLabel87
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u6e38\u620f\u4fe1\u606f\u9009\u62e9\u60a8\u8981ban\u7684\u6e38\u620fid\uff01");

		jLabel88.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel88.setForeground(new java.awt.Color(255, 255, 255));
		jLabel88.setText("ID\uff1a");

		jTextField7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton35.setBackground(new java.awt.Color(255, 0, 51));
		jButton35.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton35.setForeground(new java.awt.Color(255, 255, 255));
		jButton35.setText("BAN");
		jButton35.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton35ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
				jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout
				.setHorizontalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel11Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel11Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel11Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel11Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel86)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel87))
																						.addGroup(
																								jPanel11Layout
																										.createSequentialGroup()
																										.addGap(
																												514,
																												514,
																												514)
																										.addComponent(
																												jLabel88)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												101,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton35)))
																		.addContainerGap())
														.addGroup(
																jPanel11Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel11Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel85)
																						.addContainerGap())
																		.addGroup(
																				jPanel11Layout
																						.createSequentialGroup()
																						.addComponent(
																								jScrollPane6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								1310,
																								Short.MAX_VALUE)
																						.addGap(
																								81,
																								81,
																								81))))));
		jPanel11Layout
				.setVerticalGroup(jPanel11Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel11Layout
										.createSequentialGroup()
										.addGap(47, 47, 47)
										.addComponent(jLabel85)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(67, 67, 67)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel86)
														.addComponent(jLabel87))
										.addGap(78, 78, 78)
										.addGroup(
												jPanel11Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel88)
														.addGroup(
																jPanel11Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton35)))
										.addContainerGap(89, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u6e38\u620f\u7ba1\u7406 ", jPanel11);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								523,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				795,
																				795,
																				795)
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												188,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel7))
																						.addComponent(
																								jLabel5)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jSeparator1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				1874,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				213,
																				213,
																				213)
																		.addComponent(
																				jTabbedPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				1479,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																185,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				45,
																				45,
																				45)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												jLabel4)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel5)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(
																																				jLabel7)
																																		.addComponent(
																																				jLabel6))))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel2)))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												769,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//ban游戏
	private void jButton35ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField7.getText())) {
			int pd = 0;
			Client c = new Client();
			String[][] dataObject = c.messagegame();
			for (int i = 0; i < dataObject.length; i++) {
				if (dataObject[i][0].equals(this.jTextField7.getText())) {
					Client c1 = new Client();
					c1.bangame(this.jTextField7.getText());
					JOptionPane.showMessageDialog(this, "BAN游戏成功！");
					view_game();
					pd = 1;
				}
			}
			if (pd == 0) {
				JOptionPane.showMessageDialog(this, "您输入的游戏不存在！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	//查看游戏
	private void view_game() throws IOException, ClassNotFoundException {
		this.jLabel6.setText(m.getAdmin());
		Client c = new Client();
		String[] tableString = { "id", "游戏名", "价格", "介绍图片地址", "游戏地址", "游戏介绍",
				"状态", "上传时间", "下载量", "收藏度" };
		Object[][] dataObject = c.messagegame();
		this.jTable6.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable6.setDefaultRenderer(Object.class, cr);
	}

	//ban商家
	private void jButton34ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField6.getText())) {
			int pd = 0;
			Client c = new Client();
			Object[][] dataObject = c.view_merchant();
			for (int i = 0; i < dataObject.length; i++) {
				if (dataObject[i][0].equals(this.jTextField6.getText())) {
					Client c1 = new Client();
					c1.banmerchant(this.jTextField6.getText());
					JOptionPane.showMessageDialog(this, "BAN商家成功！");
					view_merchant();
					pd = 1;
				}
			}
			if (pd == 0) {
				JOptionPane.showMessageDialog(this, "您输入的商店不存在！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	//查看商家
	private void view_merchant() throws IOException, ClassNotFoundException {
		Client c = new Client();
		String[] tableString = { "id", "商店名", "邮箱", "密码", "小金库", "状态" };
		Object[][] dataObject = c.view_merchant();
		if (dataObject != null) {
			this.jTable5
					.setModel(new DefaultTableModel(dataObject, tableString));
			DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
			cr.setHorizontalAlignment(JLabel.CENTER);
			this.jTable5.setDefaultRenderer(Object.class, cr);
		}
	}

	//ban用户
	private void jButton36ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField8.getText())
				&& !"".equals(this.jTextField3.getText())) {
			int pd = 0;
			Client c = new Client();
			Object[][] dataObject = c.usermessage();
			for (int i = 0; i < dataObject.length; i++) {
				if (dataObject[i][0].equals(this.jTextField8.getText())) {
					Client c1 = new Client();
					c1.banuser(this.jTextField8.getText(), this.jTextField3
							.getText());
					JOptionPane.showMessageDialog(this, "BAN用户成功！");
					view_user();
					pd = 1;
				}
			}
			if (pd == 0) {
				JOptionPane.showMessageDialog(this, "您输入的用户不存在！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	//查看用户信息
	private void view_user() throws IOException, ClassNotFoundException {
		Client c = new Client();
		String[] tableString = { "id", "用户名", "邮箱", "密码", "状态", "BAN理由" };
		Object[][] dataObject = c.usermessage();
		if (dataObject != null) {
			this.jTable7
					.setModel(new DefaultTableModel(dataObject, tableString));
			DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
			cr.setHorizontalAlignment(JLabel.CENTER);
			this.jTable7.setDefaultRenderer(Object.class, cr);
		}
	}

	//删除评论
	private void jButton32ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField4.getText())) {
			int pd = 0;
			Client c = new Client();
			Object[][] dataObject = c.allcommentlist();
			if (dataObject.length == 1) {
				JOptionPane.showMessageDialog(this, "最后一个评论不能被删除，请保留最后一个声音！");
			} else {
				for (int i = 0; i < dataObject.length; i++) {
					if (dataObject[i][0].equals(this.jTextField4.getText())) {
						Client c1 = new Client();
						c1.deletecommentlist(this.jTextField4.getText());
						JOptionPane.showMessageDialog(this, "删除评论成功！");
						view_commentlist();
						pd = 1;
					}
				}
				if (pd == 0) {
					JOptionPane.showMessageDialog(this, "不存在该评论！");
				}
			}
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	//查看评论
	private void view_commentlist() throws IOException, ClassNotFoundException {
		Client c = new Client();
		String[] tableString = { "id", "用户名", "内容", "游戏名" };
		Object[][] dataObject = c.allcommentlist();
		if (dataObject != null) {
			this.jTable3
					.setModel(new DefaultTableModel(dataObject, tableString));
			DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
			cr.setHorizontalAlignment(JLabel.CENTER);
			this.jTable3.setDefaultRenderer(Object.class, cr);
		}
	}

	//删除公告
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField2.getText())) {
			if (Pattern.matches("^[0-9]+$", this.jTextField2.getText())) {
				//int id = Integer.valueOf(this.jTextField2.getText()).intValue();
				int pd = 0;
				Client c = new Client();
				Object[][] dataObject = c.announcement();
				if (dataObject.length == 1) {
					JOptionPane.showMessageDialog(this,
							"最后一个公告不能被删除，请保留最后一个公告！");
				} else {
					for (int i = 0; i < dataObject.length; i++) {
						if (dataObject[i][0].equals(this.jTextField2.getText())) {
							Client c1 = new Client();
							c1.deleteannouncement(this.jTextField2.getText());
							JOptionPane.showMessageDialog(this, "删除公告成功！");
							view_announcement();
							pd = 1;
						}
					}
					if (pd == 0) {
						JOptionPane.showMessageDialog(this, "不存在该公告！");
					}
				}
				//announcement_massage_view();
			} else {
				JOptionPane.showMessageDialog(this, "请输入正确的ID！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "请填写你要删除的公告的ID！");
		}
	}

	//添加公告
	String data;

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		if (!"".equals(this.jTextField1.getText())) {
			data = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
					.format(new Date());
			if (!this.jTextField1.getText().equals("")) {
				Client c = new Client();
				c.newannouncement(this.jTextField1.getText(), data);
				JOptionPane.showMessageDialog(this, "发布公告成功！");
				view_announcement();
				//announcement_massage_view();
			} else {
				JOptionPane.showMessageDialog(this, "请填写要发布的公告内容！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "请完善信息！");
		}
	}

	//查看公告
	private void view_announcement() throws IOException, ClassNotFoundException {
		Client c = new Client();
		String[] tableString = { "id", "发布时间", "公告内容" };
		Object[][] dataObject = c.announcement();
		this.jTable1.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable1.setDefaultRenderer(Object.class, cr);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton32;
	private javax.swing.JButton jButton34;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton36;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel66;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel75;
	private javax.swing.JLabel jLabel76;
	private javax.swing.JLabel jLabel77;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel81;
	private javax.swing.JLabel jLabel82;
	private javax.swing.JLabel jLabel83;
	private javax.swing.JLabel jLabel84;
	private javax.swing.JLabel jLabel85;
	private javax.swing.JLabel jLabel86;
	private javax.swing.JLabel jLabel87;
	private javax.swing.JLabel jLabel88;
	private javax.swing.JLabel jLabel89;
	private javax.swing.JLabel jLabel90;
	private javax.swing.JLabel jLabel91;
	private javax.swing.JLabel jLabel92;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable3;
	private javax.swing.JTable jTable5;
	private javax.swing.JTable jTable6;
	private javax.swing.JTable jTable7;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration//GEN-END:variables

}