/*
 * merchant_view.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import server.Client;

import model.Management;
import model.Merchant;

/**
 *
 * @author  __USER__
 */
public class merchant_view extends javax.swing.JFrame {

	private Merchant m;

	public merchant_view(Merchant m) throws IOException,
			ClassNotFoundException, SQLException {
		this.m = m;
		initComponents();
		this.setLocationRelativeTo(null);
		//查看游戏
		game();
		game2();
		game3();
		this.jLabel6.setText(m.getMername());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jSeparator1 = new javax.swing.JSeparator();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jLabel90 = new javax.swing.JLabel();
		jScrollPane8 = new javax.swing.JScrollPane();
		jTable8 = new javax.swing.JTable();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel89 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTable7 = new javax.swing.JTable();
		jLabel8 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jLabel85 = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTable6 = new javax.swing.JTable();
		jLabel86 = new javax.swing.JLabel();
		jLabel87 = new javax.swing.JLabel();
		jLabel88 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jButton35 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(41, 45, 51));

		jPanel2.setBackground(new java.awt.Color(41, 45, 51));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/image/图标.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("Bauhaus 93", 3, 24));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Because of your creation and more perfect");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3
				.setText("\u56e0\u60a8\u7684\u521b\u9020\u800c\u66f4\u52a0\u5b8c\u7f8e");

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/view/image/建议头像.png"))); // NOI18N

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel5.setForeground(new java.awt.Color(51, 102, 255));
		jLabel5.setText("\u6b22\u8fce\u60a8\uff1a");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6
				.setText("\u611f\u89c9\u4eba\u751f\u8fbe\u5230\u4e86\u5dc5\u5cf0");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel7.setForeground(new java.awt.Color(0, 102, 255));
		jLabel7.setText("\u5546\u5bb6");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																523,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												782, Short.MAX_VALUE)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				188,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel7))
														.addComponent(jLabel5))
										.addGap(68, 68, 68)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																185,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				47,
																				47,
																				47)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				39,
																				39,
																				39)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel6)
																														.addComponent(
																																jLabel7)))
																						.addComponent(
																								jLabel4))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jTabbedPane1.setForeground(new java.awt.Color(0, 204, 255));
		jTabbedPane1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		jPanel3.setBackground(new java.awt.Color(51, 51, 51));

		jLabel90.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel90.setForeground(new java.awt.Color(255, 255, 255));
		jLabel90.setText("\u6e38\u620f\u4fe1\u606f\uff1a");

		jTable8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable8.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable8.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane8.setViewportView(jTable8);

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("\u6dfb\u52a0\u6e38\u620f\uff1a");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jLabel12.setForeground(new java.awt.Color(204, 204, 204));
		jLabel12
				.setText("\u8bf7\u5b8c\u5584\u4f60\u8981\u6dfb\u52a0\u7684\u6e38\u620f\u8be6\u7ec6\u4fe1\u606f\uff1a");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("\u6e38\u620f\u540d\uff1a");

		jTextField3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("\u6e38\u620f\u4ef7\u683c\uff1a");

		jTextField4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jTextField5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("\u6e38\u620f\u7f51\u5740\uff1a");

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("\u6e38\u620f\u4ecb\u7ecd\uff1a");

		jButton4.setBackground(new java.awt.Color(0, 255, 0));
		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("\u6dfb\u52a0");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton4ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(77, 77, 77)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel17)
																						.addComponent(
																								jLabel11))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel12)
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel13)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												Short.MAX_VALUE)
																																										.addComponent(
																																												jTextField3,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												254,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel15)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jTextField5,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												254,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																																		.addGap(
																																				59,
																																				59,
																																				59)
																																		.addComponent(
																																				jLabel14)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jTextField4,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				254,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel18,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												289,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								1063,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				72,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton4))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel90)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				1213,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jScrollPane8,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																1333,
																Short.MAX_VALUE))
										.addGap(87, 87, 87)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addComponent(jLabel90)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				29,
																				29,
																				29)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jLabel12))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel13)
																						.addComponent(
																								jLabel14)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel15)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				46,
																				46,
																				46)
																		.addComponent(
																				jLabel18,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				118,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				57,
																				57,
																				57)
																		.addComponent(
																				jLabel17)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton4))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				99,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(38, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u6dfb\u52a0\u6e38\u620f ", jPanel3);

		jPanel4.setBackground(new java.awt.Color(51, 51, 51));

		jLabel89.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel89.setForeground(new java.awt.Color(255, 255, 255));
		jLabel89.setText("\u8bc4\u8bba\u4fe1\u606f\uff1a");

		jTable7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable7.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable7.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane7.setViewportView(jTable7);

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8
				.setText("\u67e5\u770b\u5bf9\u5e94\u6e38\u620f\u6240\u6709\u8bc4\u8bba\uff1a");

		jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel9.setForeground(new java.awt.Color(204, 204, 204));
		jLabel9.setText("\u6e38\u620f\u540d\uff1a");

		jButton1.setBackground(new java.awt.Color(102, 102, 102));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton1.setForeground(new java.awt.Color(204, 204, 204));
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("\u56de\u590d\u8bc4\u8bba\uff1a");

		jButton2.setBackground(new java.awt.Color(102, 102, 102));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton2.setForeground(new java.awt.Color(204, 204, 204));
		jButton2.setText("\u56de\u590d");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton2ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addGap(
																				43,
																				43,
																				43)
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				196,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton1)
																		.addGap(
																				720,
																				720,
																				720))
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel89)
																						.addContainerGap())
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				jPanel4Layout
																						.createSequentialGroup()
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												jPanel4Layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel10)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextField2,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																1207,
																																Short.MAX_VALUE))
																										.addComponent(
																												jScrollPane7,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												1333,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButton2))
																						.addGap(
																								81,
																								81,
																								81))))));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(47, 47, 47)
										.addComponent(jLabel89)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(39, 39, 39)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addGap(37, 37, 37)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																105,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton2)
										.addContainerGap(54, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u56de\u590d\u8bc4\u8bba ", jPanel4);

		jPanel5.setBackground(new java.awt.Color(51, 51, 51));

		jLabel85.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel85.setForeground(new java.awt.Color(255, 255, 255));
		jLabel85.setText("\u6e38\u620f\u4fe1\u606f\uff1a");

		jTable6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jTable6.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable6.setGridColor(new java.awt.Color(0, 0, 0));
		jScrollPane6.setViewportView(jTable6);

		jLabel86.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel86.setForeground(new java.awt.Color(255, 255, 255));
		jLabel86.setText("Ban\u6e38\u620f\uff1a");

		jLabel87.setForeground(new java.awt.Color(204, 204, 204));
		jLabel87
				.setText("\u8bf7\u6839\u636e\u4e0a\u56fe\u6e38\u620f\u4fe1\u606f\u9009\u62e9\u60a8\u8981ban\u7684\u6e38\u620fid\uff01");

		jLabel88.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel88.setForeground(new java.awt.Color(255, 255, 255));
		jLabel88.setText("ID\uff1a");

		jTextField7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton35.setBackground(new java.awt.Color(255, 0, 51));
		jButton35.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton35.setForeground(new java.awt.Color(255, 255, 255));
		jButton35.setText("BAN");
		jButton35.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton35ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel5Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel5Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel86)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel87))
																						.addGroup(
																								jPanel5Layout
																										.createSequentialGroup()
																										.addGap(
																												514,
																												514,
																												514)
																										.addComponent(
																												jLabel88)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												101,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton35)))
																		.addContainerGap())
														.addGroup(
																jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel5Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel85)
																						.addContainerGap())
																		.addGroup(
																				jPanel5Layout
																						.createSequentialGroup()
																						.addComponent(
																								jScrollPane6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								1333,
																								Short.MAX_VALUE)
																						.addGap(
																								81,
																								81,
																								81))))));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(47, 47, 47)
										.addComponent(jLabel85)
										.addGap(35, 35, 35)
										.addComponent(
												jScrollPane6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												315,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(67, 67, 67)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel86)
														.addComponent(jLabel87))
										.addGap(78, 78, 78)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel88)
														.addGroup(
																jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton35)))
										.addContainerGap(109, Short.MAX_VALUE)));

		jTabbedPane1.addTab(" \u7981\u6b62\u6e38\u620f ", jPanel5);

		jPanel8.setBackground(new java.awt.Color(51, 51, 51));

		jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel19.setForeground(new java.awt.Color(255, 255, 255));
		jLabel19.setText("\u6e38\u620f\u4fe1\u606f\uff1a");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("\u4fee\u6539\u6e38\u620f\u4ef7\u683c\uff1a");

		jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21.setText("\u6e38\u620fID\uff1a");

		jTextField8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel22.setForeground(new java.awt.Color(255, 255, 255));
		jLabel22.setText("\u65b0\u6e38\u620f\u4ef7\u683c\uff1a");

		jTextField9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton5.setBackground(new java.awt.Color(102, 102, 102));
		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton5.setForeground(new java.awt.Color(204, 204, 204));
		jButton5.setText("\u66f4\u65b0\u4ef7\u683c");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton5ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(118, 118, 118)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel20)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																1252,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel19))
										.addContainerGap(127, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel8Layout
										.createSequentialGroup()
										.addContainerGap(396, Short.MAX_VALUE)
										.addComponent(jLabel21)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												204,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel22)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												196,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26).addComponent(
												jButton5).addGap(371, 371, 371)));
		jPanel8Layout
				.setVerticalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGap(80, 80, 80)
										.addComponent(jLabel19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												271,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(60, 60, 60)
										.addComponent(jLabel20)
										.addGap(101, 101, 101)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel21)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel22)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton5))
										.addContainerGap(123, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jTabbedPane1.addTab(" \u4fee\u6539\u6e38\u620f\u4ef7\u683c ", jPanel6);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jSeparator1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1911,
						Short.MAX_VALUE).addGroup(
						jPanel1Layout.createSequentialGroup().addGap(199, 199,
								199).addComponent(jTabbedPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1502,
								javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(210, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												157,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(1, 1, 1)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												794,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//ban游戏
	private void jButton35ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException, SQLException {
		// TODO add your handling code here:
		int pd = 0;
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.merchantgame(m.getMername());
		for (int i = 0; i < dataObject.length; i++) {
			if (dataObject[i][0].equals(this.jTextField7.getText())) {
				Client c1 = new Client();
				c1.bangame(this.jTextField7.getText());
				JOptionPane.showMessageDialog(this, "BAN游戏成功！");
				game();
				game2();
				game3();
				pd = 1;
			}
		}
		if (pd == 0) {
			JOptionPane.showMessageDialog(this, "不存在该游戏！");
		}
	}

	//修改游戏价格
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException, SQLException {
		// TODO add your handling code here:
		int pd = 0;
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.merchantgame(m.getMername());
		for (int i = 0; i < dataObject.length; i++) {
			if (dataObject[i][0].equals(this.jTextField8.getText())) {
				Client c1 = new Client();
				c1.newprice(this.jTextField8.getText(), this.jTextField9
						.getText());
				JOptionPane.showMessageDialog(this, "修改价格成功！");
				game();
				game2();
				game3();
				pd = 1;
			}
		}
		if (pd == 0) {
			JOptionPane.showMessageDialog(this, "不存在该游戏！");
		}
	}

	//回复评论
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here:
		Client c1 = new Client();
		if (this.jTextField2.getText() != null
				&& this.jTextField1.getText() != null) {
			c1.reply(m.getMername(), this.jTextField2.getText(),
					this.jTextField1.getText());
			view_commentlist();
			JOptionPane.showMessageDialog(this, "评论成功！");
		} else {
			JOptionPane.showMessageDialog(this, "评论失败！");
		}
	}

	//查看评论
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException {
		// TODO add your handling code here
		int pd = 0;
		int pd2 = 0;
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.allcommentlist();
		Client c2 = new Client();
		String[][] dataObject2 = c2.messagegame();
		for (int i = 0; i < dataObject.length; i++) {
			if (dataObject[i][3].equals(this.jTextField1.getText())) {
				view_commentlist();
				pd = 1;
			}
		}
		for (int j = 0; j < dataObject2.length; j++) {
			if (dataObject2[j][1].equals(this.jTextField1.getText())) {
				pd2 = 1;
			}
		}
		if (pd2 == 0) {
			JOptionPane.showMessageDialog(this, "不存在该游戏！");
		}
		if (pd2 == 1) {
			if (pd == 1) {
				JOptionPane.showMessageDialog(this, "查看评论成功！");
			}
			if (pd == 0) {
				JOptionPane.showMessageDialog(this, "该游戏还没有人评论！");
			}
		}
	}

	private void view_commentlist() throws IOException, ClassNotFoundException {
		String[] tableString = { "id", "评论者", "内容", "对应游戏" };
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c
				.view_commentlist(this.jTextField1.getText());
		this.jTable7.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable7.setDefaultRenderer(Object.class, cr);
	}

	//添加游戏
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException, ClassNotFoundException, SQLException {
		// TODO add your handling code here:
		int pd = 1;
		Client c = new Client();
		String[][] dataObject = c.messagegame();
		for (int i = 0; i < dataObject.length; i++) {
			if (dataObject[i][1].equals(this.jTextField3.getText())) {
				pd = 0;
			}
		}
		if (pd == 1) {
			Client c1 = new Client();
			if (this.jTextField3.getText() != null
					&& this.jTextField4.getText() != null
					&& this.jTextField5.getText() != null
					&& this.jTextField6.getText() != null) {
				String data = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
						.format(new Date());
				//System.out.println(m.getMername());
				c1.addgame(this.jTextField3.getText(), this.jTextField4
						.getText(), this.jTextField5.getText(),
						this.jTextField6.getText(), data, m.getMername());
				Client c2 = new Client();
				c2.reply(m.getMername(), "请点评该游戏", this.jTextField3.getText());
				JOptionPane.showMessageDialog(this, "添加游戏成功");
				game();
				game2();
				game3();
			}
		}
		if (pd == 0) {
			JOptionPane.showMessageDialog(this, "该游戏已存在，如有疑问请联系客服10086！");
		}
	}

	//查看游戏
	private void game() throws IOException, ClassNotFoundException,
			SQLException {
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.merchantgame(m.getMername());
		String[] tableString = { "id", "游戏名", "价格", "游戏地址", "游戏介绍", "状态",
				"上传时间", "发布商店名", "下载量", "收藏度" };
		this.jTable8.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable8.setDefaultRenderer(Object.class, cr);
	}

	private void game2() throws IOException, ClassNotFoundException {
		String[] tableString = { "id", "游戏名", "价格", "游戏地址", "游戏介绍", "状态",
				"上传时间", "发布商店名", "下载量", "收藏度" };
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.merchantgame(m.getMername());
		this.jTable6.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable6.setDefaultRenderer(Object.class, cr);
	}

	private void game3() throws IOException, ClassNotFoundException {
		String[] tableString = { "id", "游戏名", "价格", "游戏地址", "游戏介绍", "状态",
				"上传时间", "发布商店名", "下载量", "收藏度" };
		Client c = new Client();
		Object[][] dataObject = (Object[][]) c.merchantgame(m.getMername());
		this.jTable1.setModel(new DefaultTableModel(dataObject, tableString));
		DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
		cr.setHorizontalAlignment(JLabel.CENTER);
		this.jTable1.setDefaultRenderer(Object.class, cr);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new merchant_view(null).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton35;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel85;
	private javax.swing.JLabel jLabel86;
	private javax.swing.JLabel jLabel87;
	private javax.swing.JLabel jLabel88;
	private javax.swing.JLabel jLabel89;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel90;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable6;
	private javax.swing.JTable jTable7;
	private javax.swing.JTable jTable8;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}